# Generated by Django 3.2.8 on 2021-11-26 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('building_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'building',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('credits', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('building_id', models.ForeignKey(blank=True, db_column='building_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studentApp.building')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('inst_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('dept_name', models.ForeignKey(blank=True, db_column='dept_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studentApp.department')),
            ],
            options={
                'db_table': 'instructor',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('building_id', models.OneToOneField(db_column='building_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='studentApp.building')),
                ('room_no', models.IntegerField()),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'classroom',
                'unique_together': {('building_id', 'room_no')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('course_id', models.OneToOneField(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='studentApp.course')),
                ('section_id', models.IntegerField()),
                ('semester', models.CharField(max_length=6)),
                ('section_year', models.TextField()),
                ('timeslot_id', models.IntegerField()),
                ('building_id', models.ForeignKey(db_column='building_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_classroom_buildingno', to='studentApp.classroom')),
                ('room_no', models.ForeignKey(db_column='room_no', on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_classroom_roomno', to='studentApp.classroom')),
            ],
            options={
                'db_table': 'section',
                'unique_together': {('course_id', 'section_id', 'semester', 'section_year')},
            },
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('timeslot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=5)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'timeslot',
                'unique_together': {('timeslot_id', 'day', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.IntegerField(primary_key=True, serialize=False)),
                ('route_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shuttle_id', models.CharField(blank=True, max_length=5, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('timeslot_id', models.ForeignKey(blank=True, db_column='timeslot_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studentApp.timeslot')),
            ],
            options={
                'db_table': 'route',
            },
        ),
        migrations.CreateModel(
            name='InstPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('journal', models.CharField(blank=True, max_length=200, null=True)),
                ('publication_year', models.TextField(blank=True, null=True)),
                ('inst_id', models.ForeignKey(db_column='inst_id', on_delete=django.db.models.deletion.DO_NOTHING, to='studentApp.instructor')),
            ],
            options={
                'db_table': 'inst_publication',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='dept_name',
            field=models.ForeignKey(blank=True, db_column='dept_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studentApp.department'),
        ),
        migrations.CreateModel(
            name='InstField',
            fields=[
                ('inst_id', models.OneToOneField(db_column='inst_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='studentApp.instructor')),
                ('field_of_interest', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'inst_field',
                'unique_together': {('inst_id', 'field_of_interest')},
            },
        ),
        migrations.CreateModel(
            name='InstDegree',
            fields=[
                ('inst_id', models.OneToOneField(db_column='inst_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='studentApp.instructor')),
                ('degree_name', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('degree_year', models.TextField()),
            ],
            options={
                'db_table': 'inst_degree',
                'unique_together': {('inst_id', 'degree_name', 'institution', 'country', 'degree_year')},
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.IntegerField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=100)),
                ('route_id', models.ForeignKey(db_column='route_id', on_delete=django.db.models.deletion.DO_NOTHING, to='studentApp.route')),
            ],
            options={
                'db_table': 'driver',
                'unique_together': {('driver_id', 'driver_name', 'route_id')},
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='loginApp.student')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='studentcourse_section_courseid', to='studentApp.section')),
                ('section_id', models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='studentcourse_section_sectionid', to='studentApp.section')),
                ('semester', models.ForeignKey(db_column='semester', on_delete=django.db.models.deletion.DO_NOTHING, related_name='studentcourse_section_semester', to='studentApp.section')),
            ],
            options={
                'db_table': 'student_course',
                'unique_together': {('student_id', 'course_id', 'section_id', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Prereq',
            fields=[
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='prereq_course_course', serialize=False, to='studentApp.course')),
                ('prereq_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prereq_course_prereq', to='studentApp.course')),
            ],
            options={
                'db_table': 'prereq',
                'unique_together': {('course_id', 'prereq_id')},
            },
        ),
        migrations.CreateModel(
            name='InstTeaches',
            fields=[
                ('inst_id', models.OneToOneField(db_column='inst_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='studentApp.instructor')),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='instteaches_section_courseid', to='studentApp.section')),
                ('section_id', models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='instteaches_section_sectionid', to='studentApp.section')),
                ('section_year', models.ForeignKey(db_column='section_year', on_delete=django.db.models.deletion.DO_NOTHING, related_name='instteaches_section_sectionyear', to='studentApp.section')),
                ('semester', models.ForeignKey(db_column='semester', on_delete=django.db.models.deletion.DO_NOTHING, related_name='instteaches_section_semester', to='studentApp.section')),
            ],
            options={
                'db_table': 'inst_teaches',
                'unique_together': {('inst_id', 'course_id', 'section_id', 'semester', 'section_year')},
            },
        ),
    ]
