# Generated by Django 3.2.8 on 2021-11-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('building_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'building',
            },
        ),
    ]
