# Generated by Django 3.2.8 on 2021-11-29 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('building_id', models.ForeignKey(db_column='building_id', on_delete=django.db.models.deletion.DO_NOTHING, to='studentApp.building')),
            ],
            options={
                'db_table': 'classroom',
                'unique_together': {('building_id', 'room_no')},
            },
        ),
    ]
