# Generated by Django 3.2.8 on 2021-11-28 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('building_id', models.OneToOneField(db_column='building_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='studentApp.building')),
                ('room_no', models.IntegerField()),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'classroom',
                'unique_together': {('building_id', 'room_no')},
            },
        ),
    ]
