# Generated by Django 3.2.8 on 2021-11-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
