# Generated by Django 3.2.8 on 2021-11-29 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0002_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('building_id', models.ForeignKey(blank=True, db_column='building_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studentApp.building')),
            ],
            options={
                'db_table': 'department',
            },
        ),
    ]
