# Generated by Django 3.2.8 on 2021-11-11 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0002_alter_course_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('dept_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('building', models.CharField(default='Main', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=3),
        ),
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('building', models.CharField(default='Main', max_length=100, primary_key=True, serialize=False)),
                ('room_no', models.IntegerField()),
                ('capacity', models.IntegerField(null=True)),
            ],
            options={
                'unique_together': {('building', 'room_no')},
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='dept_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.department'),
        ),
    ]
