# Generated by Django 3.2.8 on 2021-12-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0003_alter_route_route_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='status',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
