# Generated by Django 3.2.8 on 2021-11-11 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0003_auto_20211111_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='instructor',
            fields=[
                ('inst_id', models.IntegerField(primary_key=True, serialize=False)),
                ('inst_name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=50)),
                ('designation', models.CharField(default='Lecturer', max_length=50)),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='inst_field',
            fields=[
                ('inst_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='studentApp.instructor')),
                ('field_of_interest', models.CharField(max_length=500)),
            ],
            options={
                'unique_together': {('inst_id', 'field_of_interest')},
            },
        ),
    ]
