# Generated by Django 3.2.8 on 2021-11-11 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0004_inst_field_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='inst_degree',
            fields=[
                ('inst_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='studentApp.instructor')),
                ('degree_name', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('year', models.IntegerField(max_length=3)),
            ],
            options={
                'unique_together': {('inst_id', 'degree_name', 'institution', 'country', 'year')},
            },
        ),
    ]
