# Generated by Django 3.2.8 on 2021-11-28 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0005_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstField',
            fields=[
                ('inst_id', models.OneToOneField(db_column='inst_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='studentApp.instructor')),
                ('field_of_interest', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'inst_field',
                'unique_together': {('inst_id', 'field_of_interest')},
            },
        ),
    ]
