# Generated by Django 3.2.8 on 2021-11-11 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0005_inst_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inst_degree',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
        migrations.CreateModel(
            name='inst_publication',
            fields=[
                ('inst_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='studentApp.instructor')),
                ('url', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('journal', models.CharField(max_length=200)),
                ('year', models.IntegerField(max_length=4)),
            ],
            options={
                'unique_together': {('inst_id', 'url', 'title', 'journal', 'year')},
            },
        ),
    ]
