# Generated by Django 3.2.8 on 2021-11-29 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0005_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_interest', models.CharField(max_length=50)),
                ('inst_id', models.ForeignKey(db_column='inst_id', on_delete=django.db.models.deletion.DO_NOTHING, to='studentApp.instructor')),
            ],
            options={
                'db_table': 'inst_field',
                'unique_together': {('inst_id', 'field_of_interest')},
            },
        ),
    ]
