# Generated by Django 3.2.8 on 2021-11-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0006_auto_20211111_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inst_publication',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='inst_publication',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
