# Generated by Django 3.2.8 on 2021-11-29 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0006_instfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('degree_year', models.CharField(max_length=4)),
                ('inst_id', models.ForeignKey(db_column='inst_id', on_delete=django.db.models.deletion.DO_NOTHING, to='studentApp.instructor')),
            ],
            options={
                'db_table': 'inst_degree',
                'unique_together': {('inst_id', 'degree_name', 'institution', 'country', 'degree_year')},
            },
        ),
    ]
