# Generated by Django 3.2.8 on 2021-11-28 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0007_instdegree'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('journal', models.CharField(blank=True, max_length=200, null=True)),
                ('publication_year', models.CharField(blank=True, max_length=4, null=True)),
                ('inst_id', models.ForeignKey(db_column='inst_id', on_delete=django.db.models.deletion.DO_NOTHING, to='studentApp.instructor')),
            ],
            options={
                'db_table': 'inst_publication',
            },
        ),
    ]
