# Generated by Django 3.2.8 on 2021-11-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0008_instpublication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot_id', models.CharField(max_length=10)),
                ('day', models.CharField(max_length=5)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'timeslot',
                'unique_together': {('timeslot_id', 'day', 'start_time')},
            },
        ),
    ]
