# Generated by Django 3.2.8 on 2021-11-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0008_instpublication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('timeslot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=5)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'timeslot',
                'unique_together': {('timeslot_id', 'day', 'start_time')},
            },
        ),
    ]
