# Generated by Django 3.2.8 on 2021-11-11 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0009_auto_20211111_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='building_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.building'),
        ),
    ]
