# Generated by Django 3.2.8 on 2021-11-28 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0009_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('course_id', models.OneToOneField(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='studentApp.course')),
                ('section_id', models.IntegerField()),
                ('semester', models.CharField(max_length=6)),
                ('section_year', models.CharField(max_length=4)),
                ('timeslot_id', models.IntegerField()),
                ('building_id', models.ForeignKey(db_column='building_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_classroom_buildingno', to='studentApp.classroom')),
                ('room_no', models.ForeignKey(db_column='room_no', on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_classroom_roomno', to='studentApp.classroom')),
            ],
            options={
                'db_table': 'section',
                'unique_together': {('course_id', 'section_id', 'semester', 'section_year')},
            },
        ),
    ]
