# Generated by Django 3.2.8 on 2021-11-29 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0009_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.IntegerField()),
                ('sem_code', models.CharField(max_length=8)),
                ('building_id', models.ForeignKey(db_column='building_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_classroom_buildingno', to='studentApp.building')),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, to='studentApp.course')),
                ('room_no', models.ForeignKey(db_column='room_no', on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_classroom_roomno', to='studentApp.classroom')),
                ('timeslot_id', models.ForeignKey(db_column='timeslot_id', on_delete=django.db.models.deletion.DO_NOTHING, to='studentApp.timeslot')),
            ],
            options={
                'db_table': 'section',
                'unique_together': {('course_id', 'section_id', 'sem_code')},
            },
        ),
    ]
