# Generated by Django 3.2.8 on 2021-11-28 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0010_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstTeaches',
            fields=[
                ('inst_id', models.OneToOneField(db_column='inst_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='studentApp.instructor')),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='instteaches_section_courseid', to='studentApp.section')),
                ('section_id', models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='instteaches_section_sectionid', to='studentApp.section')),
                ('section_year', models.ForeignKey(db_column='section_year', on_delete=django.db.models.deletion.DO_NOTHING, related_name='instteaches_section_sectionyear', to='studentApp.section')),
                ('semester', models.ForeignKey(db_column='semester', on_delete=django.db.models.deletion.DO_NOTHING, related_name='instteaches_section_semester', to='studentApp.section')),
            ],
            options={
                'db_table': 'inst_teaches',
                'unique_together': {('inst_id', 'course_id', 'section_id', 'semester', 'section_year')},
            },
        ),
    ]
