# Generated by Django 3.2.8 on 2021-11-29 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0010_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstTeaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='instteaches_section_courseid', to='studentApp.course')),
                ('inst_id', models.ForeignKey(db_column='inst_id', on_delete=django.db.models.deletion.DO_NOTHING, to='studentApp.instructor')),
                ('section_id', models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='instteaches_section_sectionid', to='studentApp.section')),
                ('sem_code', models.ForeignKey(db_column='sem_code', on_delete=django.db.models.deletion.DO_NOTHING, related_name='instteaches_semcode', to='studentApp.section')),
            ],
            options={
                'db_table': 'inst_teaches',
                'unique_together': {('inst_id', 'course_id', 'section_id', 'sem_code')},
            },
        ),
    ]
