# Generated by Django 3.2.8 on 2021-11-28 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
        ('studentApp', '0011_instteaches'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='loginApp.student')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='studentcourse_section_courseid', to='studentApp.section')),
                ('section_id', models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='studentcourse_section_sectionid', to='studentApp.section')),
                ('semester', models.ForeignKey(db_column='semester', on_delete=django.db.models.deletion.DO_NOTHING, related_name='studentcourse_section_semester', to='studentApp.section')),
            ],
            options={
                'db_table': 'student_course',
                'unique_together': {('student_id', 'course_id', 'section_id', 'semester')},
            },
        ),
    ]
