# Generated by Django 3.2.8 on 2021-11-29 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
        ('studentApp', '0011_instteaches'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct1', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('ct2', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('ct3', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('quiz', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('assignment1', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('assignment2', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('mid', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='studentcourse_section_courseid', to='studentApp.section')),
                ('section_id', models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='studentcourse_section_sectionid', to='studentApp.section')),
                ('sem_code', models.ForeignKey(db_column='sem_code', on_delete=django.db.models.deletion.DO_NOTHING, related_name='studentcourse_semcode', to='studentApp.section')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loginApp.student')),
            ],
        ),
    ]
