# Generated by Django 3.2.8 on 2021-11-28 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0012_studentcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prereq',
            fields=[
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='prereq_course_course', serialize=False, to='studentApp.course')),
                ('prereq_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prereq_course_prereq', to='studentApp.course')),
            ],
            options={
                'db_table': 'prereq',
                'unique_together': {('course_id', 'prereq_id')},
            },
        ),
    ]
