# Generated by Django 3.2.8 on 2021-11-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
        ('studentApp', '0012_studentcourse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together={('student_id', 'course_id', 'section_id', 'sem_code')},
        ),
        migrations.AlterModelTable(
            name='studentcourse',
            table='student_course',
        ),
    ]
