# Generated by Django 3.2.8 on 2021-11-11 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0012_auto_20211111_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='timeslot_id',
            field=models.ForeignKey(default='Not assigned', on_delete=django.db.models.deletion.DO_NOTHING, to='studentApp.timeslot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='day',
            field=models.CharField(default='Not assigned', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='timeslot_id',
            field=models.CharField(default='Not assigned', max_length=5, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('timeslot_id', 'day', 'start_time')},
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='id',
        ),
    ]
