# Generated by Django 3.2.8 on 2021-11-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0013_auto_20211111_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='sem_code',
            field=models.CharField(default='', max_length=5),
        ),
    ]
