# Generated by Django 3.2.8 on 2021-11-29 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0013_auto_20211129_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prereq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prereq_course_course', to='studentApp.course')),
                ('prereq_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prereq_course_prereq', to='studentApp.course')),
            ],
            options={
                'db_table': 'prereq',
                'unique_together': {('course_id', 'prereq_id')},
            },
        ),
    ]
