# Generated by Django 3.2.8 on 2021-11-28 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0013_prereq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.IntegerField(primary_key=True, serialize=False)),
                ('route_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shuttle_id', models.CharField(blank=True, max_length=5, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('timeslot_id', models.ForeignKey(blank=True, db_column='timeslot_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studentApp.timeslot')),
            ],
            options={
                'db_table': 'route',
            },
        ),
    ]
