# Generated by Django 3.2.8 on 2021-11-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0014_auto_20211111_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='prereq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
