# Generated by Django 3.2.8 on 2021-11-11 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0015_prereq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prereq',
        ),
    ]
