# Generated by Django 3.2.8 on 2021-11-29 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0015_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField()),
                ('driver_name', models.CharField(max_length=100)),
                ('route_id', models.ForeignKey(db_column='route_id', on_delete=django.db.models.deletion.DO_NOTHING, to='studentApp.route')),
            ],
            options={
                'db_table': 'driver',
                'unique_together': {('driver_id', 'driver_name', 'route_id')},
            },
        ),
    ]
