# Generated by Django 3.2.8 on 2021-11-29 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0016_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='studentcourse_section_courseid', to='studentApp.course'),
        ),
    ]
