# Generated by Django 3.2.8 on 2021-11-11 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0016_delete_prereq'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='section',
        ),
        migrations.DeleteModel(
            name='timeslot',
        ),
    ]
