# Generated by Django 3.2.8 on 2021-11-11 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0017_auto_20211111_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='timeslot',
            fields=[
                ('timeslot_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=3)),
                ('start_time', models.TimeField(default='20:00')),
                ('end_time', models.TimeField(default='20:00')),
            ],
            options={
                'unique_together': {('timeslot_id', 'day', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('section_id', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('sem_code', models.CharField(default='', max_length=5)),
                ('building', models.CharField(default='Main', max_length=100)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studentApp.course')),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studentApp.classroom')),
                ('timeslot_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studentApp.timeslot')),
            ],
            options={
                'unique_together': {('course_id', 'section_id', 'sem_code')},
            },
        ),
    ]
