# Generated by Django 3.2.8 on 2021-11-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0018_section_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='timeslot_id',
            field=models.CharField(default='', max_length=5, primary_key=True, serialize=False),
        ),
    ]
