# Generated by Django 3.2.8 on 2021-11-26 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('fullname', models.CharField(default='UNKNOWN', max_length=200)),
                ('department', models.CharField(default='UNKNOWN', max_length=10)),
                ('semester', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('address', models.CharField(default='UNKNOWN', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
