# Generated by Django 3.2.8 on 2021-11-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_alter_student_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='dept_name',
            field=models.CharField(default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='UNKNOWN', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
