# Generated by Django 3.2.8 on 2021-11-10 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0003_auto_20211110_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='fullname',
        ),
    ]
