# Generated by Django 3.2.8 on 2021-11-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0004_rename_name_student_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='dept_name',
            new_name='department',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='UNKNOWN', max_length=500),
        ),
    ]
